#!/bin/bash

# Exit the script if any of the commands fail
set -e
set -u
set -o pipefail

# Set working directory to the location of this script
cd "$(dirname "${BASH_SOURCE[0]}")"

# Use "~" in place of "-" in NPMVERSION to make dpkg sort pre-releases correctly
# See https://github.com/thelounge/thelounge-deb/issues/58

# Some variables
NPMVERSION=$(grep Version debian/control | awk -F': ' '{print $2}' | sed -E 's/-[0-9]+$//' | sed -E 's/~/-/')
STARTDIR="$(pwd)"
DESTDIR="$STARTDIR/pkg"
OUTDIR="$STARTDIR/deb"
CACHE="$STARTDIR/cache"
MODULES_DIR="$DESTDIR/usr/lib/thelounge/node_modules"
export HOME="$STARTDIR" # because yarn is stupid and tries to mess with the user config files

echo "Building $NPMVERSION..."

# Remove potential leftovers from a previous build
rm -rf "$DESTDIR" "$OUTDIR"

install -dm755 "$DESTDIR/usr/bin"
install -dm755 "$MODULES_DIR/thelounge"

# Fetch the lock file so that we actually get the pinned deps that we want
curl -O "https://raw.githubusercontent.com/thelounge/thelounge/$NPMVERSION/yarn.lock"

# Install the package itself
# we on purposes don't use yarn global add, because with it --ignore-scripts
# is pointless: https://github.com/yarnpkg/yarn/issues/8291 but we tried
yarn add --no-default-rc --frozen-lockfile \
	--prod --non-interactive --ignore-scripts \
	--cache-folder "$CACHE" --modules-folder "$MODULES_DIR" \
	"thelounge@${NPMVERSION}"

# Write .thelounge_home to set correct system config directory
echo "/etc/thelounge" > "$MODULES_DIR/thelounge/.thelounge_home"

# manually write the binary link
ln -s "${MODULES_DIR#$DESTDIR}/thelounge/index.js" "$DESTDIR/usr/bin/thelounge"

# Install configuration/home directory
install -dm775 "$DESTDIR/etc/thelounge"
install -dm770 "$DESTDIR/etc/thelounge/users"
install -Dm660 \
	"$MODULES_DIR/thelounge/dist/defaults/config.js" \
	"$DESTDIR/etc/thelounge/config.js"

# Install systemd units
install -Dm644 "$STARTDIR/systemd/system.service" \
	"$DESTDIR/lib/systemd/system/thelounge.service"
install -Dm644 "$STARTDIR/systemd/user.service" \
	"$DESTDIR/usr/lib/systemd/user/thelounge.service"

# Build .deb
mkdir "$DESTDIR/DEBIAN" "$OUTDIR"
cp "$STARTDIR/debian/"* "$DESTDIR/DEBIAN/"
dpkg-deb --root-owner-group --build "$DESTDIR" "$OUTDIR"
