#!/bin/bash

# Exit the script if any of the commands fail
set -e
set -u
set -o pipefail

# Set working directory to the location of this script
cd "$(dirname "${BASH_SOURCE[0]}")"

# Some variables
THELOUNGEVERSION=$(grep Version debian/control | awk -F': ' '{print $2}' | sed -E 's/-[0-9]+$//')
STARTDIR="$(pwd)"
DESTDIR="$STARTDIR/pkg"
OUTDIR="$STARTDIR/deb"
YARNDIR="$STARTDIR/yarn"

echo "Building $THELOUNGEVERSION..."

# Remove potential leftovers from a previous build
rm -rf "$DESTDIR" "$OUTDIR" "$YARNDIR"

# Download Yarn
mkdir "$YARNDIR"
wget https://yarnpkg.com/latest-rc.tar.gz -O "$YARNDIR/yarn.tar.gz"
tar zvxf "$YARNDIR/yarn.tar.gz" -C "$YARNDIR"

YARNBINARY="$STARTDIR/$(find "$YARNDIR" -name yarn.js -type f)"

# Install the package itself
node "$YARNBINARY" \
	--cache-folder "$YARNDIR" \
	--cwd "$DESTDIR/usr/lib/node_modules/thelounge" \
	--non-interactive \
	--ignore-optional \
	--no-default-rc \
	--production \
	"thelounge@${THELOUNGEVERSION}"

# Write .thelounge_home to set correct system config directory
echo "/etc/thelounge" > "$DESTDIR/usr/lib/node_modules/thelounge/.thelounge_home"

# Install configuration/home directory
install -dm775 "$DESTDIR/etc/thelounge"
install -dm770 "$DESTDIR/etc/thelounge/users"
install -Dm660 \
	"$DESTDIR/usr/lib/node_modules/thelounge/defaults/config.js" \
	"$DESTDIR/etc/thelounge/config.js"

# Install systemd units
install -Dm644 "$STARTDIR/systemd/system.service" \
	"$DESTDIR/lib/systemd/system/thelounge.service"
install -Dm644 "$STARTDIR/systemd/user.service" \
	"$DESTDIR/usr/lib/systemd/user/thelounge.service"
install -dm755 "$DESTDIR/lib/systemd/system/multi-user.target.wants"
ln -s "../thelounge.service" \
	"$DESTDIR/lib/systemd/system/multi-user.target.wants/thelounge.service"

# Build .deb
mkdir "$DESTDIR/DEBIAN" "$OUTDIR"
cp "$STARTDIR/debian/"* "$DESTDIR/DEBIAN/"
dpkg-deb --build "$DESTDIR" "$OUTDIR"
