#!/bin/bash
[[ "$1" == "configure" ]] || exit 0

if ! getent group thelounge >/dev/null; then
	echo 'Creating thelounge group'
	addgroup --quiet --system thelounge
fi

if ! getent passwd thelounge >/dev/null; then
	echo 'Creating thelounge user'
	adduser --quiet --system thelounge \
		--ingroup thelounge \
		--no-create-home \
		--gecos "System user for The Lounge (IRC client)"
fi

chown -R thelounge:thelounge /etc/thelounge

deb-systemd-helper enable thelounge.service
deb-systemd-invoke start thelounge.service || echo "could not start thelounge.service automatically"
