#!/bin/bash
set -e

[[ "$1" == "configure" ]] || exit 0

if ! getent group thelounge >/dev/null; then
	addgroup --quiet --system thelounge
fi

if ! getent passwd thelounge >/dev/null; then
	adduser --quiet --system thelounge \
		--ingroup thelounge \
		--home /etc/thelounge/ \
		--gecos "thelounge system user"
fi

chown -R thelounge:thelounge /etc/thelounge
systemctl daemon-reload
systemctl start thelounge.service
