#!/bin/bash
set -euo pipefail

[[ "$1" == "install" ]] || exit 0

# TODO: Remove this in a few versions after v3 to help transitioning
if [ -f /etc/lounge/config.js ] && [ ! -d /etc/thelounge ]; then
	mv /etc/lounge /etc/thelounge
	echo 'The directory /etc/lounge/ has been moved to /etc/thelounge/'
fi

